name: Issue
description: Create a new issue
title: "Summarise the issue here"
body:
  - type: markdown
    attributes:
      value: |
        Using the following template describe the issue  
        What:
        Why:
        Who (will benefit) :
        How (are we doing this now):
        Technical caveats:
        

  - type: textarea
    id: technical_specifics
    attributes:
      label: Technical specifics
      description: Provide the technical details or environment information relevant to the issue.
      placeholder: Describe any logs, configurations, or system details here.
