name: Issue
description: Create a new issue
title: "Add repo to the title!"
body:
  - type: markdown
    attributes:
      value: |
        Using the following template describe the issue
        For: *users of the software or developers*
        Who: *want this thing*
        The: *issue is with X*
        Is a: *broad solution*
        that: *That achieves what?*
        unlike: *Presently or alternatives*
        our solution: *will work*

        Technical specifics:
        *put the technical specifics here*
