name: Issue
description: Create a new issue
title: "Add repo to the title!"
body:
  - type: markdown
    attributes:
      value: |
        Using the following template describe the issue  
        For: *users of the software or developers*  
        Who: *want this thing*  
        The: *issue is with X*  
        Is a: *broad solution*  
        That: *achieves what?*  
        Unlike: *presently or alternatives*  
        Our solution: *will work*

  - type: textarea
    id: technical_specifics
    attributes:
      label: Technical specifics
      description: Provide the technical details or environment information relevant to the issue.
      placeholder: Describe any logs, configurations, or system details here.
