name: Issue
description: Create a new issue
title: "Add repo to the title!"
body:
  - type: markdown
    attributes:
      value: |
        Hopefully this should simplify creating issues across the repositories, please feel free to complain to me directly if not.
        Things to add:
          - [ ] Project
          - [ ] Size estimate
          - [ ] Priority
          - [ ] Title has been changed (Including the repo in the title, e.g.: Add code coverage for IR-API, Improve deployment of CEPH mounting in k8s)
  - type: textarea
    id: issue-description
    attributes:
      label: Description of the issue
      description: Give a brief description of what needs to happen
    validations:
      required: true
